# Generated by Django 4.2.1 on 2023-08-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
